// <auto-generated />
using ElectroShop.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectroShop.Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20221123171543_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectroShop.Shared.Entities.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            ManufacturerName = "Motorola"
                        },
                        new
                        {
                            ManufacturerId = 2,
                            ManufacturerName = "Apple"
                        });
                });

            modelBuilder.Entity("ElectroShop.Shared.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 139108825,
                            ManufacturerId = 1,
                            Price = 1749f,
                            ProductName = "Motorola Edge 30 Neo 8/128GB Czarny"
                        },
                        new
                        {
                            ProductId = 139108829,
                            ManufacturerId = 1,
                            Price = 1749f,
                            ProductName = "Motorola Edge 30 Neo 8/128GB Fioletowy"
                        },
                        new
                        {
                            ProductId = 139120876,
                            ManufacturerId = 1,
                            Price = 1749f,
                            ProductName = "Motorola Edge 30 Neo 8/128GB Srebrny"
                        },
                        new
                        {
                            ProductId = 113375066,
                            ManufacturerId = 1,
                            Price = 1749f,
                            ProductName = "Motorola Edge 20 8/128GB Czarny"
                        },
                        new
                        {
                            ProductId = 138536499,
                            ManufacturerId = 2,
                            Price = 6999f,
                            ProductName = "iPhone 14 Pro"
                        });
                });

            modelBuilder.Entity("ElectroShop.Shared.Entities.ProductDescription", b =>
                {
                    b.Property<int>("ProductDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductDescriptionId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductLongDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductDescriptionId");

                    b.ToTable("ProductDescriptions");

                    b.HasData(
                        new
                        {
                            ProductDescriptionId = 1,
                            ProductId = 139108825,
                            ProductLongDescription = "Ultrasmukły i lekki, z kinowym ekranem 6,28\", oferowany w najnowszych modnych kolorach Pantone. \r\nSystem aparatów 64 Mpx z OIS \r\nRób krystalicznie wyraźne zdjęcia w wysokiej rozdzielczości w każdym oświetleniu, \r\njednocześnie eliminując rozmycia na skutek przypadkowego poruszenia aparatem.",
                            ProductShortDescription = "Smartfon Motorola z ekranem 6,7 cala, wyświetlacz OLED. Aparat 108 Mpix, pamięć 8 GB RAM, bateria 4000mAh. Obsługuje sieć: 5G"
                        },
                        new
                        {
                            ProductDescriptionId = 2,
                            ProductId = 139108829,
                            ProductLongDescription = "Ultrasmukły i lekki, z kinowym ekranem 6,28\", oferowany w najnowszych modnych kolorach Pantone. \r\nSystem aparatów 64 Mpx z OIS \r\nRób krystalicznie wyraźne zdjęcia w wysokiej rozdzielczości w każdym oświetleniu, \r\njednocześnie eliminując rozmycia na skutek przypadkowego poruszenia aparatem.",
                            ProductShortDescription = "Smartfon Motorola z ekranem 6,7 cala, wyświetlacz OLED. Aparat 108 Mpix, pamięć 8 GB RAM, bateria 4000mAh. Obsługuje sieć: 5G"
                        },
                        new
                        {
                            ProductDescriptionId = 3,
                            ProductId = 139120876,
                            ProductLongDescription = "Ultrasmukły i lekki, z kinowym ekranem 6,28\", oferowany w najnowszych modnych kolorach Pantone. \r\nSystem aparatów 64 Mpx z OIS \r\nRób krystalicznie wyraźne zdjęcia w wysokiej rozdzielczości w każdym oświetleniu, \r\njednocześnie eliminując rozmycia na skutek przypadkowego poruszenia aparatem.",
                            ProductShortDescription = "Smartfon Motorola z ekranem 6,7 cala, wyświetlacz OLED. Aparat 108 Mpix, pamięć 8 GB RAM, bateria 4000mAh. Obsługuje sieć: 5G"
                        },
                        new
                        {
                            ProductDescriptionId = 4,
                            ProductId = 113375066,
                            ProductLongDescription = "Ultrasmukły i lekki, z kinowym ekranem 6,28\", oferowany w najnowszych modnych kolorach Pantone. \r\nSystem aparatów 64 Mpx z OIS \r\nRób krystalicznie wyraźne zdjęcia w wysokiej rozdzielczości w każdym oświetleniu, \r\njednocześnie eliminując rozmycia na skutek przypadkowego poruszenia aparatem.",
                            ProductShortDescription = "Smartfon Motorola z ekranem 6,7 cala, wyświetlacz OLED. Aparat 108 Mpix, pamięć 8 GB RAM, bateria 4000mAh. Obsługuje sieć: 5G"
                        },
                        new
                        {
                            ProductDescriptionId = 5,
                            ProductId = 138536499,
                            ProductLongDescription = "Ultrasmukły i lekki, z kinowym ekranem 6,28\", oferowany w najnowszych modnych kolorach Pantone. \r\nSystem aparatów 64 Mpx z OIS \r\nRób krystalicznie wyraźne zdjęcia w wysokiej rozdzielczości w każdym oświetleniu, \r\njednocześnie eliminując rozmycia na skutek przypadkowego poruszenia aparatem.",
                            ProductShortDescription = "Smartfon Apple z ekranem 6,1 cala, wyświetlacz Super Retina XDR. Aparat 48 Mpix, pamięć 4 GB RAM. Obsługuje sieć: 5G"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
