// <auto-generated />
using Basket.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Basket.Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20221211104052_Basket")]
    partial class Basket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectroShop.Shared.Domain.BasketItem", b =>
                {
                    b.Property<int>("BasketItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BasketItemId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BasketItemId");

                    b.ToTable("BasketItems");

                    b.HasData(
                        new
                        {
                            BasketItemId = 1,
                            Amount = 2,
                            Price = 3498m,
                            ProductId = 139108829,
                            UserId = 1
                        },
                        new
                        {
                            BasketItemId = 2,
                            Amount = 1,
                            Price = 1749m,
                            ProductId = 139120876,
                            UserId = 1
                        },
                        new
                        {
                            BasketItemId = 3,
                            Amount = 1,
                            Price = 1749m,
                            ProductId = 138536499,
                            UserId = 1
                        },
                        new
                        {
                            BasketItemId = 4,
                            Amount = 1,
                            Price = 1749m,
                            ProductId = 139120876,
                            UserId = 2
                        },
                        new
                        {
                            BasketItemId = 5,
                            Amount = 1,
                            Price = 1749m,
                            ProductId = 138536499,
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
